services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: air
    env_file: config.env
    volumes:
      - .:/app
      - go_data:/go
    depends_on:
      - db
      - test_db

  db:
    image: postgres:17.4-alpine3.21
    restart: always
    env_file: config.env
    volumes:
      - ./init.sql/:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - 54321:5432

  test_db:
    image: postgres:17.4-alpine3.21
    restart: always
    env_file: config.env
    volumes:
      - testdb_data:/var/lib/postgresql/data

volumes:
  db_data:
  testdb_data:
  go_data:
