
FROM golang:1.24.1 AS builder

WORKDIR /app

RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o wallets_api .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/wallets_api /usr/local/bin/wallets_api

RUN ls -l /usr/local/bin/wallets_api

RUN chmod +x /usr/local/bin/wallets_api

CMD ["wallets_api"]

EXPOSE 8080
