name: Go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: setup config.env
        run: |
            touch config.env
            echo DB_USER=$POSTGRES_USER >> config.env
            echo DB_PASSWORD=$POSTGRES_PASSWORD >> 'config.env'
            echo TEST_DB_HOST=postgres >> 'config.env'
            echo DB_HOST=localhost >> 'config.env'
            echo DB_PORT="5432" >> 'config.env'

      - run: make install
      - run: make build
      - run: make test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile.production
          cache-from: ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline
          tags: ghcr.io/${{ github.repository }}:latest
